<a href="https://colab.research.google.com/github/yuyangweng/edge-computing/blob/main/logicgates_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras import models
from keras import layers
from keras.layers import Dense, Dropout
import numpy as np


In [13]:
def logical_gate(X,Y): 
    model = models.Sequential()
    model.add(Dense(8, activation='relu', input_shape=(2,),name='layer1'))
    model.add(Dense(16, activation='relu',name='layer2'))
    #model.add(Dense(1, activation='sigmoid')) # if y is 0 or 1
    model.add(Dense(1, activation='tanh',name='layer3')) # if y is 0 or 1
    #print(model.summary())
    model.compile(optimizer='adam', loss='mse', metrics=['accuracy']) # binary_crossentropy
   
    model.fit(X, Y,epochs=200,verbose=1) 
    return model

  
def gate_predict_prob(model,X):
    return model.predict(X)


def gate_predict(model,X):
    return np.round(model.predict(X))

def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))


In [3]:
X_train=np.array([[0., 0.],[0., 1.],[1., 0.],[1., 1.]])
Y_train=np.array([0,1,1,0]) 
xor_gate=logical_gate(X_train,Y_train)
gate_predict(xor_gate,X_train)


Epoch 1/200
1/1 [==============================] - 14s 14s/step - loss: 0.5070 - accuracy: 0.5000
Epoch 2/200
1/1 [==============================] - 0s 5ms/step - loss: 0.4939 - accuracy: 0.5000
Epoch 3/200
1/1 [==============================] - 0s 6ms/step - loss: 0.4811 - accuracy: 0.5000
Epoch 4/200
1/1 [==============================] - 0s 8ms/step - loss: 0.4688 - accuracy: 0.5000
Epoch 5/200
1/1 [==============================] - 0s 7ms/step - loss: 0.4568 - accuracy: 0.5000
Epoch 6/200
1/1 [==============================] - 0s 12ms/step - loss: 0.4451 - accuracy: 0.5000
Epoch 7/200
1/1 [==============================] - 0s 6ms/step - loss: 0.4339 - accuracy: 0.5000
Epoch 8/200
1/1 [==============================] - 0s 6ms/step - loss: 0.4230 - accuracy: 0.5000
Epoch 9/200
1/1 [==============================] - 0s 7ms/step - loss: 0.4125 - accuracy: 0.5000
Epoch 10/200
1/1 [==============================] - 0s 6ms/step - loss: 0.4023 - accuracy: 0.5000
Epoch 11/200
1/1 [=========

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [4]:
xor_gate.predict(X_train)

array([[0.18024263],
       [0.7964949 ],
       [0.7112078 ],
       [0.08069269]], dtype=float32)

In [5]:
X_train=np.array([[0., 0.],[0., 1.],[1., 0.],[1., 1.]])
Y_train=np.array([0,0,0,1])

and_gate=logical_gate(X_train,Y_train)
gate_predict(and_gate,X_train)

Epoch 1/200
1/1 [==============================] - 1s 782ms/step - loss: 0.2269 - accuracy: 0.5000
Epoch 2/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2236 - accuracy: 0.5000
Epoch 3/200
1/1 [==============================] - 0s 6ms/step - loss: 0.2203 - accuracy: 0.5000
Epoch 4/200
1/1 [==============================] - 0s 7ms/step - loss: 0.2170 - accuracy: 0.5000
Epoch 5/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2138 - accuracy: 0.5000
Epoch 6/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2106 - accuracy: 0.5000
Epoch 7/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2074 - accuracy: 0.5000
Epoch 8/200
1/1 [==============================] - 0s 5ms/step - loss: 0.2043 - accuracy: 0.5000
Epoch 9/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2012 - accuracy: 0.5000
Epoch 10/200
1/1 [==============================] - 0s 4ms/step - loss: 0.1982 - accuracy: 0.5000
Epoch 11/200
1/1 [=========

array([[-0.],
       [ 0.],
       [ 0.],
       [ 1.]], dtype=float32)

## save model & load model

In [6]:
from keras.models import load_model
# creates a HDF5 file
xor_gate.save('xor_gate.h5')

In [7]:
#load model
xor_gate=load_model ('xor_gate.h5')
x=np.array([1,1]).reshape(1,2)
print(gate_predict(xor_gate,x))
print(gate_predict_prob(xor_gate,x))

[[0.]]
[[0.08069263]]


In [8]:
xor_gate.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (None, 8)                 24        
_________________________________________________________________
layer2 (Dense)               (None, 16)                144       
_________________________________________________________________
layer3 (Dense)               (None, 1)                 17        
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________


In [9]:
layer_names=[layer.name for layer in xor_gate.layers]
layer_names

['layer1', 'layer2', 'layer3']

In [10]:
import h5py

# 模型地址
MODEL_PATH = 'xor_gate.h5'

# 獲取每一層的連接權重及偏重
print("讀取模型中...")
with h5py.File(MODEL_PATH, 'r') as f:
    dense_1 = f['/model_weights/layer1/layer1']
    dense_1_bias =  dense_1['bias:0'][:]
    dense_1_kernel = dense_1['kernel:0'][:]

    dense_2 = f['/model_weights/layer2/layer2']
    dense_2_bias = dense_2['bias:0'][:]
    dense_2_kernel = dense_2['kernel:0'][:]

    dense_3 = f['/model_weights/layer3/layer3']
    dense_3_bias = dense_3['bias:0'][:]
    dense_3_kernel = dense_3['kernel:0'][:]

print("第一層的連接weight矩陣：\n%s\n"%dense_1_kernel)
print("第一層的連接bias矩陣：\n%s\n"%dense_1_bias)
print("第二層的連接weight矩陣：\n%s\n"%dense_2_kernel)
print("第二層的連接bias矩陣：\n%s\n"%dense_2_bias)
print("第三層的連接weight矩陣：\n%s\n"%dense_3_kernel)
print("第三層的連接bias矩陣：\n%s\n"%dense_3_bias)

讀取模型中...
第一層的連接weight矩陣：
[[ 0.24905501 -0.339099   -0.12128493 -0.42329693 -0.70107776 -0.67215127
   0.63423157 -0.23021457]
 [ 0.16203013 -0.21602756  0.79687893 -0.3137589   0.23085931  0.66411394
  -0.00731821  0.83181304]]

第一層的連接bias矩陣：
[ 0.00306694  0.          0.06789368  0.         -0.0154349   0.00773847
  0.08891645  0.15645568]

第二層的連接weight矩陣：
[[-0.38696623 -0.12253991  0.0934083   0.12008546 -0.00566578  0.40662643
   0.47881636  0.37053555  0.39380884 -0.03174127 -0.01976946 -0.177175
   0.4709144   0.32313803 -0.25729766  0.43209478]
 [ 0.06520236  0.47239304 -0.21638238 -0.23086226  0.02741468 -0.46196914
  -0.26876318 -0.19474137  0.3693912  -0.29719603 -0.4176445   0.3814255
  -0.3785485  -0.32519352 -0.40759957 -0.11734462]
 [-0.06501132  0.17263384 -0.23867549 -0.21026795 -0.46341693 -0.18885984
  -0.38282272  0.12471607  0.2865164  -0.47667062  0.15295742  0.516979
  -0.2816005  -0.36028752  0.3374961  -0.14877528]
 [-0.04141843  0.36702788 -0.00165403 -0.2415868 

In [11]:
def relu(x):
    return np.maximum(0, x)

In [14]:

x=np.array([1,1])
print('name:',xor_gate.layers[0].name)
weights, biases = xor_gate.layers[0].get_weights()
x=np.dot(x,weights)+biases
x=relu(x)
print('name:',xor_gate.layers[1].name)
weights, biases = xor_gate.layers[1].get_weights()
x=np.dot(x,weights)+biases
x=relu(x)
print('name:',xor_gate.layers[2].name)
weights, biases = xor_gate.layers[2].get_weights()
x=np.dot(x,weights)+biases
x=tanh(x)
print('x:',x)

name: layer1
name: layer2
name: layer3
x: [0.08069262]
